DEVICE=SANREMO
OBJS=\
$(BIN)\alloc.obj\
$(BIN)\interrup.obj\
$(BIN)\loopback.obj\
$(BIN)\packet.obj\
$(BIN)\request.obj\
$(BIN)\lance.obj\
$(BIN)\send.obj\
$(BIN)\transfer.obj\
$(BIN)\ndisdev.obj

!include .\ndis.mk
